recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeAuthorListView,
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    ShoppingItemListView,
    create_shopping_item,
    delete_all_shopping_items,
    log_rating,
    RecipeDetailView,
    RecipeListView,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path("users/", RecipeAuthorListView.as_view(), name="recipe_users"),
    path("shopping_items/create/", create_shopping_item, name="shopping_item_create"),
    path("shopping_items/", ShoppingItemListView.as_view(), name="shopping_item_list"),
    path("shopping_items/delete/", delete_all_shopping_items, name="shopping_item_delete")
]

scrumptious/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView, TagDetailView, TagDeleteView, TagCreateView, TagUpdateView
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

recipes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
    USER_MODEL, related_name="recipes",
    on_delete=models.CASCADE, null=True,
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        USER_MODEL, related_name="recipe_update",
        on_delete=models.CASCADE, null=True,
    )
    servings = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)], null=True)

    def __str__(self):
        return self.name + " by " + str(self.author)

class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name + " - " + self.abbreviation

class FoodItem(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Ingredient(models.Model):
    amount = models.FloatField(validators=[MaxValueValidator(20), MinValueValidator(1)])
    recipe = models.ForeignKey(Recipe, related_name="ingredients", on_delete=models.CASCADE)
    measure = models.ForeignKey(Measure, on_delete=models.PROTECT)
    food = models.ForeignKey(FoodItem, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.recipe) + " " + str(self.measure) + " " + str(self.food)

class Step(models.Model):
    recipe = models.ForeignKey(Recipe, related_name="steps", on_delete=models.CASCADE)
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.recipe) + " " + str(self.directions)

class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )

class ShoppingItem(models.Model):
    user = models.ForeignKey(USER_MODEL, related_name="shopping_items", on_delete=models.CASCADE)
    food_item = models.ForeignKey("FoodItem", related_name="shopping_item", on_delete=models.PROTECT, unique=True, null=True)

recipes/forms.py
from django import forms
from recipes.models import Rating



from recipes.models import Recipe


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

recipes/views.py
from pprint import pprint
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.decorators.http import require_http_methods
from django.contrib.auth.models import User


from recipes.forms import RatingForm


from recipes.models import USER_MODEL, Ingredient, Recipe, ShoppingItem




class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = ["name", "description", "image", "servings"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "description", "image", "servings"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)

class RecipeListView(ListView):
    paginate_by = 4
    model = Recipe
    template_name = "recipes/list.html"

class RecipeAuthorListView(ListView):
    paginate_by = 4
    model = User
    template_name = "recipes/users.html"
    context_object_name = "users"


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()
        #Create a new empty list and assign it to a variable
        foods = []
        # For each item in the user's shopping items, which we
        # can access through the code.
        # self.request.user.shopping_items.all()
        for item in self.request.user.shopping_items.all():
        #test1 = self.request.user.shopping_items.all()
        #test2 = self.request.shopping_item.user
            #Add the shopping item's food to the list
            foods.append(item.food_item)
        # the self.request.GET property is a dictionary
        #get the value out of there associated w/ the key "servings"
        # store in the context dictionary w/ the key servings
        context["servings"] = self.request.GET.get("servings")

        # Put that list into the context
        context["food_in_shopping_list"] = foods

        return context


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")

def log_rating(request, recipe_id):
    if request.method == "POST":
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            try:
                rating.recipe = Recipe.objects.get(pk=recipe_id)
            except Recipe.DoesNotExist:
                return redirect("recipes_list")
            rating.save()
    return redirect("recipe_detail", pk=recipe_id)

#view 1 -- Create
    # function form
@require_http_methods(["POST"])
def create_shopping_item(request):
    #get the value for the "ingredient_id" from the
    # request.POST dictionary using the "get" method
    ingredient_id = request.POST.get("ingredient_id")
    #get the specific ingredient from the Ingredient model
    ingredient = Ingredient.objects.get(id=ingredient_id)
    # get the current user
    user = request.user
    try:
        #Create the new shopping item in the database
        ShoppingItem.objects.create(food_item=ingredient.food,user=user)
    #catch the error if its already in there
    except IntegrityError:
        #Don't do anything w/ the error
        pass
    #Go back to the recipe page
    return redirect("recipe_detail", pk=ingredient.recipe.id)

#view 2 -- List
    # class form
    #wlil show a list of shopping items that was created by the user. Not all shopping items
class ShoppingItemListView(LoginRequiredMixin, ListView):
    model = ShoppingItem
    template_name = "shopping_items/list.html"

    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)

#view 3 -- Delete
    # function form

def delete_all_shopping_items(request):
    #Delete all of the shopping items for the user
    #using code like
    #ShoppingItem.objects.filter(user=the current user).delete()

    #GO back to the shopping item list with a redirect
    #to the name of the registered shopping item list
    # path with code like this
    # return redirect(
    # name of the reqistered shopping item list path
    # )

    ShoppingItem.objects.filter(user=request.user).delete()
    return redirect("shopping_item_list")

recipes/templates/recipes/delete.html
{% extends 'base.html' %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ recipe }}"?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>
{% endblock content %}

recipes/templates/recipes/detail.html
{% extends 'base.html' %} {% block content %} {% load resizer %} {% load markdownify %}

<main class="recipe-detail">
  <div>
    <a href="{% url 'recipe_edit' recipe.id %}">Edit</a>
    <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
  </div>
  {% if recipe.image %}
  <img src="{{ recipe.image }}" class="pull-right" />
  {% endif %}
  <h1>{{ recipe.name }}</h1>
  <h2>by: {{ recipe.author | default_if_none:"Unknown" }}</h2>
  <p>
    Created on {{ recipe.created }} | Updated on {{ recipe.updated }} by
    {{recipe.updated_by | default_if_none:"N/A" }}
  </p>
  {% if recipe.servings %}
  <p>Serves {{ servings|default_if_none:recipe.servings }}</p>

  <form method="GET">
    <input required type="number" name="servings" />
    <button>Resize</button>
  </form>

  {% endif %}

  <form method="post" action="{% url 'recipe_rating' recipe.id %}">
    {% csrf_token %} {{ rating_form.as_p }}
    <button class="button">Rate</button>
  </form>
  <p>Tags: {% for tag in recipe.tags.all %}{{ tag.name }} {% endfor %}</p>
  {{ recipe.description | markdownify }}
  <h2>Ingredients</h2>
  <table>
    <thead>
      <tr>
        <th colspan="2">Amount</th>
        <th>Food item</th>
      </tr>
    </thead>
    <tbody>
      {% for ingredient in recipe.ingredients.all %}
      <tr>
        <td>{{ ingredient|resize_to:servings }}</td>
        <td>{{ ingredient.measure.name }}</td>
        <td>{{ ingredient.food.name }}</td>
        <td>
          {% if ingredient.food not in food_in_shopping_list %}

          <form method="POST" action="{% url 'shopping_item_create' %}">
            {% csrf_token %}
            <input type="hidden" name="ingredient_id" value="{{ ingredient.id }}" />
            <button>+ shopping list</button>
          </form>
        </td>
        {% else %}
        <td>
          <p>in your list</p>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <h2>Steps</h2>
  <ol>
    {% for step in recipe.steps.all %}
    <li>{{ step.directions }}</li>
    {% endfor %}
  </ol>
</main>
{% endblock content %}

recipes/templates/recipes/edit.html
{% extends 'base.html' %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'paginate.html' %} {% block content %}
<main class="recipe-grid">
  {% for recipe in recipe_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </h2>
    <p class="recipe-card-date">{{ recipe.updated }}</p>
  </div>
  {% endfor %}
</main>
{% endblock content %}

recipes/templates/recipes/new.html
{% extends 'base.html' %} {% block content %}

<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

recipes/templates/recipes/users.html
{% extends 'paginate.html' %} {% block content %}
<main class="recipe-grid">
  <div>
  {% for user in users %}

  <div class="recipe-card">
    <h2 class="recipe-card-title">
      {{ user.username }}
    </h2>
  <ul>

    {% for recipe in user.recipes.all %}
    <li>
     <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </li>
  {% endfor %}
</ul>

</div>

  {% endfor %}




</main>
{% endblock content %}